# 
#  scales.yml: pitch sets expressed as JI ratios
#  
#  Copyright November 2010, Adam Florin. All rights reserved.
# 
# /2s
# --
# 3/2 - P5
# 
# /3s
# --
# 4/3 - P4
# 5/3 - M6
# 
# /4s
# --
# 5/4 - M3
# 7/4 - nat. 7  
# 
# /5s
# --
# 6/5 - m3
# 7/5 - TT
# 8/5 - m6
# 9/5 - m7
# 
# /8s
# --
# ...
# 15/8 - M7
# 

# JI "major" scale (?)... very sweet + endearing
major_ji: [1.0, 9/8.0, 5/4.0, 4/3.0, 3/2.0, 5/3.0, 7/4.0]
    
# JI "octotonic"... a bit square with those high prime numerators
octotonic_ji: [1.0, 9/8.0, 5/4.0, 11/8.0, 3/2.0, 13/8.0, 7/4.0, 15/8.0]

# JI "pentatonic" scale... off-kilter quality
pentatonic_ji: [5/5.0, 6/5.0, 7/5.0, 8/5.0, 9/5.0]

# JI "mixto"
mixto_ji: [1.0, 6/5.0, 5/4.0, 3/2.0, 8/5.0, 7/4.0, 9/5.0]

# 
western: [1.0, 6/5.0, 7/5.0, 3/2.0]

# (penta + stables): U, m3, P4, TT, P5, m6, M7
new_western: [1.0, 9/8.0, 6/5.0, 5/3.0, 7/5.0, 3/2.0, 8/5.0]

abeja: [1.0, 9/8.0, 5/4.0, 15/8.0]
